logLevel:

cache-adapters:
  - identifier: PrimaryCacheAdapter
    type: GoCache
    evict-time-hours: 24
    evict-schedule-time-hours: 2

routers:
  - type: ReverseProxy
    pattern: /api/v1/
    target-url: http://localhost:8081/
    filters:
      - type: SessionFilter
        name: Session filter v1
        session-cookie: session
        cookie-ttl-hours: 24
        renew-cookie-before-hours: 6
        cache-adapter-identifier: PrimaryCacheAdapter

      - type: LogFilter
        name: Simple requests log
        template: "METHOD:{{.Request.Method}} PATH:{{.Request.URL}} SESSION_ID:{{(.Request.Context.Value \"SessionContextKey\").Id}}\n"

  - type: ReverseProxy
    pattern: /api/v2/
    target-url: http://localhost:8081/
    filters:
      - type: SessionFilter
        name: Session filter v2
        session-cookie: session
        cookie-ttl-hours: 24
        renew-cookie-before-hours: 6
        cache-adapter-identifier: PrimaryCacheAdapter

      - type: LogFilter
        name: Simple requests log
        template: "METHOD:{{.Request.Method}} PATH:{{.Request.URL}} SESSION_ID:{{(.Request.Context.Value \"SessionContextKey\").Id}}\n"
