logLevel:
routers:
  - type: ReverseProxy
    pattern: /
    target-url: http://localhost:8081/
    filters:
      - type: SessionFilter
        name: Main session filter
        session-cookie: session
        cookie-ttl-hours: 24
        renew-cookie-before-hours: 6
        cache-adapter:
          type: GoCache
          evict-time-hours: 24
          evict-schedule-time-hours: 2

      - type: LogFilter
        name: Simple requests log
        template: "METHOD:{{.Request.Method}} PATH:{{.Request.URL}}\n"