log-level: info

cache-adapters:
  - identifier: PrimaryCacheAdapter
    type: GoCache
    evict-time-hours: 24
    evict-schedule-time-hours: 2

routers:
  - type: GoogleOauth2Authorization
    pattern: /authentication/google
    success-login-url: /api/v2/
    cache-adapter-identifier: PrimaryCacheAdapter
    filters:
      - type: SessionFilter
        name: Autentication session filter
        cache-adapter-identifier: PrimaryCacheAdapter
        cookie-domain: localhost
        cookie-path: /api/v2
        cookie-name: session
        cookie-ttl-hours: 24
        cookie-renew-before-hours: 6

  - type: ReverseProxy
    pattern: /api/v1/
    target-url: http://localhost:8081/
    filters:
      - type: SessionFilter
        name: Session filter v1
        cache-adapter-identifier: PrimaryCacheAdapter
        cookie-domain: localhost
        cookie-path: /
        cookie-name: session
        cookie-ttl-hours: 24
        cookie-renew-before-hours: 6

      - type: LogFilter
        name: Simple requests log
        template: "METHOD:{{.Request.Method}} PATH:{{.Request.URL}} SESSION_ID:{{(.Request.Context.Value \"SessionContextKey\").Id}}"

  - type: ReverseProxy
    pattern: /api/v2/
    target-url: http://localhost:8081/
    filters:
      - type: SessionFilter
        name: Session filter v2
        cache-adapter-identifier: PrimaryCacheAdapter
        cookie-domain: localhost
        cookie-path: /
        cookie-name: session
        cookie-ttl-hours: 24
        cookie-renew-before-hours: 6

      - type: UserAuthenticationFilter
        name: Autentication user data filter
        cache-adapter-identifier: PrimaryCacheAdapter

      - type: LogFilter
        name: Simple requests log
        template: "METHOD:{{.Request.Method}} PATH:{{.Request.URL}} SESSION_ID:{{(.Request.Context.Value \"SessionContextKey\").Id}} USERNAME:{{(.Request.Context.Value \"UserDataContextKey\").Username}}"
